schemaId: aerobeat.environment.v1
schemaVersion: 1
recordVersion: 1
environmentId: ab-environment-splat-demo
environmentName: Gaussian Splat Demo Environment
type: splat
resourcePath: ../media/splats/countryside-farm/countryside-farm.compressed.ply
