schemaId: aerobeat.environment.v1
schemaVersion: 1
recordVersion: 1
environmentId: ab-environment-image-demo
environmentName: Image Demo Environment
type: image_background
resourcePath: ../media/images/perfect-hue-may-14-2026/perfect-hue-may-14-2026.png
