schemaId: aerobeat.environment.v1
schemaVersion: 1
recordVersion: 1
environmentId: ab-environment-video-demo
environmentName: Video Demo Environment
type: video_background
resourcePath: ../media/videos/calm_blue_sea_1/calm_blue_sea_1.ogv
